server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    root: INFO

spring:
  jpa:
    properties:
        dialect: io.github.jhipster.domain.util.FixedH2Dialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
    hibernate:
      ddl-auto: none
      dialect: h2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./assessment;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:seed.sql';
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
    jpa:
      database-platform: io.github.jhipster.domain.util.FixedH2Dialect
      show-sql: true

ticket:
  cron: '0 */1 * * * *'